name: Kiwi IRC Web Client  
version: "1.0.0"
slug: kiwiirc_webclient
description: "Modern web IRC client for ZNC"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: manual
ports:
  8080/tcp: 8080
panel_icon: mdi:chat-processing
webui: "http://[HOST]:[PORT:8080]"
host_network: true
url: https://github.com/RUBIKOF/weechat-addon
