name: Kiwi IRC Web Client
version: "20.05.24.6"
slug: kiwiirc_webclient
description: "Official Kiwi IRC web client for ZNC"
arch:
  - amd64  # Solo amd64 por ahora
url: "https://github.com/RUBIKOF/weechat-addon"
webui: "http://[HOST]:[PORT:8080]"
panel_icon: mdi:chat-processing
ports:
  8080/tcp: 8080
host_network: true
startup: application
boot: manual
init: false
map:
  - config:rw
