name: Kiwi IRC Web Client
version: "20.05.24.7"
slug: kiwiirc_webclient
description: "Official Kiwi IRC web client for ZNC (aarch64)"
arch:
  - aarch64  # ‚Üê SOLO aarch64
url: "https://github.com/RUBIKOF/weechat-addon"
webui: "http://[HOST]:[PORT:8080]"
panel_icon: mdi:chat-processing
ports:
  8080/tcp: 8080
host_network: true
startup: application
boot: manual
init: false
map:
  - config:rw
