name: KiwiIRC Web Client
version: "1.0.0"
slug: kiwiirc_web_client
description: "Web IRC client (KiwiIRC) to use as interface for the ZNC bouncer."
url: "https://github.com/RUBIKOF/weechat-addon"

arch:
  - aarch64
  - amd64
  - armv7

startup: services
boot: auto

panel_icon: mdi:chat-outline
webui: "http://[HOST]:[PORT:7778]"

ports:
  "7778/tcp": 7778
ports_description:
  "7778/tcp": "KiwiIRC web interface"

map:
  - config:rw

schema:
  log_level: "list(trace|debug|info|warning|error|fatal)?"

build:
  args:
    BUILD_FROM: "ghcr.io/home-assistant/{ARCH}-base-debian:latest"
