name: Kiwi IRC Web Client
version: "1.0.0"
slug: kiwiirc_webclient
description: "Modern web IRC client for ZNC with theme support"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: manual
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Kiwi IRC Web Interface"
map:
  - config:rw
panel_icon: mdi:chat-processing
webui: "http://[HOST]:[PORT:8080]"
url: https://github.com/RUBIKOF/weechat-addon
host_network: true
options:
  znc_server: localhost
  znc_port: 6667
  default_channel: "#homeassistant"
schema:
  znc_server: str
  znc_port: int
  default_channel: str
