name: "ZNC IRC Bouncer"
slug: "znc"
version: "0.1.0"
description: "Bouncer IRC persistente (ZNC) para Home Assistant"
url: "https://znc.in/"
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto

ingress: false

ports:
  "6501/tcp": 6501
  "6697/tcp": 6697

map:
  - config:rw

environment:
  TZ: "America/Mexico_City"
  PUID: "0"
  PGID: "0"

image: "lscr.io/linuxserver/znc:latest"
