name: ZNC IRC Bouncer
version: "1.0.6"
slug: znc_irc_bouncer
description: "Advanced IRC bouncer with web interface"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/RUBIKOF/weechat-addon"
startup: services
boot: manual
ports:
  6667/tcp: 6667
  8888/tcp: 8888
ports_description:
  6667/tcp: "IRC Bouncer Port"
  8888/tcp: "Web Admin Interface"
map:
  - config:rw
panel_icon: mdi:chat-processing
webui: "[HOST]:[PORT:8888]"
options:
  data_dir: /config/znc
schema:
  data_dir: str?
