name: ZNC IRC Bouncer
version: "1.0.0"
slug: znc_irc_bouncer
description: "ZNC IRC bouncer with web interface"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/RUBIKOF/weechat-addon" 
webui: "http://[HOST]:[PORT:8888]"
panel_icon: mdi:chat-processing
ports:
  8888/tcp: 8888
  6667/tcp: 6667
ports_description:
  8888/tcp: "Web Interface"
  6667/tcp: "IRC Bouncer"
map:
  - config:rw
init: false
host_network: false
