name: ZNC IRC Bouncer
version: "1.0.5"
slug: znc_irc_bouncer
description: "Advanced IRC bouncer with web interface"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
url: https://github.com/RUBIKOF/weechat-addon
webui: http://[HOST]:[PORT:8888]
panel_icon: mdi:chat-processing
ports:
  6667/tcp: 6667
  8888/tcp: 8888
ports_description:
  6667/tcp: "IRC bouncer port"
  8888/tcp: "Web administration interface"
map:
  - config:rw
  - ssl:rw
options:
  ssl: false
  znc_data: /config/znc
schema:
  log_level: list(trace|debug|info|warning|error|fatal)?
  ssl: bool?
  znc_data: str?
