name: ZNC IRC Bouncer
version: "1.0.4"
slug: znc_irc_bouncer
description: "An advanced IRC bouncer"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/RUBIKOF/weechat-addon" 
webui: http://[HOST]:[PORT:8888]
panel_icon: mdi:chat-processing
ports:
  6667/tcp: 6667
  8888/tcp: 8888
map:
  - config:rw
