name: ZNC IRC Bouncer
version: "1.0.5"
slug: znc_irc_bouncer
description: "IRC bouncer with web interface"
arch:
  - aarch64
  - amd64
  - armv7
url: https://github.com/RUBIKOF/weechat-addon
startup: services
boot: manual
ports:
  6667/tcp: 6667
  8888/tcp: 8888
map:
  - config:rw
panel_icon: mdi:chat-processing
