name: Convos IRC
slug: convos
version: "0.1.3"
description: "Cliente web de IRC Convos integrado en Home Assistant."
url: "https://convos.chat/"
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto

ingress: true
ingress_port: 3000
ingress_entry: /

panel_icon: "mdi:chat-outline"
panel_title: "Convos"

# /data es persistente en HA
map:
  - data:rw

options: {}
schema: {}
