name: Convos IRC
slug: convos
version: "0.1.0"
description: "Cliente web de IRC Convos integrado en Home Assistant."
url: "https://convos.chat/"
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto

ingress: true
ingress_port: 3000
ingress_entry: /

panel_icon: "mdi:chat-outline"
panel_title: "Convos"

# Variables configurables
options:
  invite_code: ""
schema:
  invite_code: "str?"

# Directorios persistentes
map:
  - data:rw

image: "local/convos-addon"
